### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [speciling/PY202309#1]
### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week3/dict_and_set
    - 52:Undefined variable 'user'	user1_friends.add(input(f"{user}'s 1st friend name: "))
    - 53:Undefined variable 'user'	user1_friends.add(input(f"{user}'s 2nd friend name: "))    
    - 54:Undefined variable 'user'	user1_friends.add(input(f"{user}'s 3rd friend name: "))
    - 58:Undefined variable 'user'	user2_friends.add(input(f"{user}'s 1st friend name: "))
    - 59:Undefined variable 'user'	user2_friends.add(input(f"{user}'s 2nd friend name: "))    
    - 60:Undefined variable 'user'	user2_friends.add(input(f"{user}'s 3rd friend name: ")) 
         - user라는 변수가 없는데 사용되고 있습니다. user를 선언하고 값을 할당해주세요.

**Comment by speciling** [comment]
반복문을 사용했다가 아직 배우지 않은 내용이라 변경하면서 제대로 수정하지 않았었네요. 수정 완료했습니다. 감사합니다!
